### ISSUE TITLE
Build transformers for each content types

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/content-api#156]
Build transformers as per transformed documents results in the ["All" search RFC](https://github.com/wellcomecollection/docs/blob/all-search-rfc/rfcs/064-content-api-all-search/README.md)

- [x] Books https://github.com/wellcomecollection/content-api/pull/163
- [x] Events https://github.com/wellcomecollection/content-api/pull/169
- [x] Exhibition texts #171 
- [x] Exhibitions #172 
- [x] Exhibition highlight tours #173
- [x] Pages #176 
- [x] Projects
- [x] Seasons
- [x] Stories https://github.com/wellcomecollection/content-api/pull/170/
- [x] Visual stories https://github.com/wellcomecollection/content-api/pull/164
- [x] Parent transformer file that sends each document through its relevant transformer https://github.com/wellcomecollection/content-api/pull/162
- [x] Filter out `delist`ed (scheduled) events before they reach the transformer #179 
- [x] Allow for arrays to be returned from transformer #181
- [x] create new pipeline?
